go-debos/fakemachine

machine.go, machine_test.go
The rootfs stays on the initramfs which is limited to 50% of the memory
size to allow usage of data mount a tmpfs on /scratch with a maximum
size of 95% of memory (going from 1G to 1.9G of allowed space usage with
the default 2 Gigabyte of memory).
Signed-off-by: Sjoerd Simons <sjoerd.simons@collabora.co.uk>
=> Mount tmpfs on /scratch

machine.go, machine_test.go
Remove all calls of log.Fatal() family to avoid embedded call of os.Exit(1).
This breaks call of deferred functions in case of problems in library.
Change in API of methods below:
- Run()
- RunInMachineWithArgs()
- RunInMachine()
Now they return (int, error) pair.
Signed-off-by: Denis Pynkin <denis.pynkin@collabora.com>
=> Remove log.Fatal() calls from library.

cmd/fakemachine/main.go, machine.go
Let callers specify the number of available CPUs (the -smp QEMU option)
both via API or the command line.
Default to the number of system CPUs available to the process.
Signed-off-by: Emanuele Aina <emanuele.aina@collabora.com>
=> Add SetNumCPUs()/--cpus to customize the SMP value

machine.go
Check if host's directory is already mapped to fake machine internal directory.
This allows to avoid unnecessary virtual filesystem mappings.
Signed-off-by: Denis Pynkin <denis.pynkin@collabora.com>
=> Skip double adding of already mapped directories from host

machine.go
Add cache=loose and msize=262144 for 9p, for faster i/o.
From the docs:
loose = no attempts are made at consistency,
intended for exclusive, read-only mounts
msize=n	the number of bytes to use for 9p packet payload
Signed-off-by: Tomeu Vizoso <tomeu.vizoso@collabora.com>
=> Tune 9p for speed

cmd/fakemachine/main.go
It wasn't previously obvious that `-m` expects a bare number of megabytes, but `-s` expects a unit suffix like `4G`.
=> main: Clarify the units used for -m, -s

cmd/fakemachine/main.go
Print "fakemachine: Whatever error\n" if Run() fails.
Print "fakemachine: Whatever error\n" instead of just "Whatever error" if `-s` can't be parsed.
Fixes #22
=> Improve error display in fakemachine CLI utility

machine.go
This file currently assumes x86_64 Linux, so it should not be buildable
elsewhere until #18 is fixed.
=> machine: Only build on x86_64 Linux

cmd/fakemachine/main.go, machine.go
In particular this avoids having the serial port support in the
BIOS/firmware reset the user's terminal into a weird state.
Signed-off-by: Simon McVittie <smcv@collabora.com>
Fixes: #25
=> machine: Don't show boot/console messages by default

machine.go
Set the limit of open files to 4096 for processes inside of Qemu VM.
We have no configuration for limits and kernel's defaults are used.
This leads to different settings on different kernels, hardcoded limit
allow to avoid problems with too strict defaults.
Signed-off-by: Denis Pynkin <denis.pynkin@collabora.com>
=> Increase the limit for open files

machine.go
The OnFailure directive is misplaced, which can be seen by running
`debos --show-boot ...`:
fakemachine systemd[1]: /etc/systemd/system/fakemachine.service:16: Unknown lvalue 'OnFailure' in section 'Service'
This commit brings it back where it belongs, under the unit section.
Signed-off-by: Arnaud Rebillout <arnaud.rebillout@collabora.com>
=> machine: Move OnFailure directive to unit section

machine.go
unix.Utsname has byte array instead of int8/uint8 array members which
makes it simpler to convert them to strings.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
=> machine: use Utsname/Uname from golang.org/x/sys/unix to simplify string conversion

cmd/fakemachine/main.go, machine.go
While adding a feature, I came across a small section of code that hadn't been run through `gofmt` and a bug that resulted in a spurious " %s" in an error message.  This patch fixes these issues.
=> Formatting and a bug

machine.go
Several distributions (including Ubuntu) ship some of the modules we rely on compiled into the kernel. Since these modules are listed in `modules.builtin`, it’s very easy to detect and skip them.
Signed-off-by: Andrej Shadura <andrew.shadura@collabora.co.uk>
=> Don’t attempt to copy built-in modules

machine.go
Some of the commands used (e.g mkfs.ext4) are normally located under /sbin. It's 
not typical for unprivileged users to have /sbin in their $PATH so fakemachine
should add /sbin:/usr/sbin to the $PATH.
Resolves: #21
Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>
=> machine: expand $PATH with /sbin and /usr/sbin

machine.go
busybox is normally located under /bin but in fedora at least, it is located
under /sbin. So search both $PATH for the executable.
Resolves: #48
Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>
=> machine: search for busybox under $PATH

backend.go, backend_kvm.go, cmd/fakemachine/main.go, cpio/writerhelper.go, machine.go
This MR defines the base for UML support for fakemachine.
End-user functionality wise no changes have been introduced with this MR; I have abstracted the machine specific implementation detail of the machine setup into its own interface and provided an implementation for KVM.
=> machine: Abstract the KVM-specific implementation details into seperate Backend interface

backend.go
By default, if no backend is selected, the auto backend is selected.
The auto backend prefers KVM and unavailable falls back to UML.
This MR depends on #57 (and therefore #56).
=> Automatically choose backend based on heuristics 

backend_kvm.go
Currently fakemachine checks whether /dev/kvm exists to see if the
backend is supported, if the device exists but the permissions are
incorrect (i.e running as a user without acces) then fakemachine
still returns that kvm is supported but fails later with a really
unhelpful error:
$ fakemachine --backend=kvm
Could not access KVM kernel module: Permission denied
qemu-system-x86_64: failed to initialize kvm: Permission denied
error starting kvm backend: <nil>
So when checking if the kvm backend is suppored, as well as checking
if /dev/kvm exists, let's also check whether the permissions are
correct and if not, stop with an error earlier:
$ fakemachine --backend=kvm
fakemachine: kvm backend not supported: open /dev/kvm: permission denied
Signed-off-by: Christopher Obbard …
=> kvm: Check /dev/kvm permissions are correct early

cpio/writerhelper.go, machine.go
Rather than panicking, bubble up errors such that
the execution may recover correctly and the error
may be shown to the downstream user.
Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>
=> Rework panic calls into bubbled-up errors

backend.go, backend_qemu.go, backend_uml.go, machine.go
This MR reverts the Arch specific commit, splits `KernelPath()` into `KernelPath()` & `ModulePath()`, reusing the last one to implement a shorter and more common solution.
In particular: Many platforms store the kernel under `/usr/lib/modules/$uname_r/vmlinuz` - perhaps because systemd expects it, to enable hibernate.
As added bonus - there is no need for a initramdisk generator, which tends to be responsible for copying the kernel in `/boot`.
Tl:Dr: Shorter, more generic code and fewer dependencies \o/
Big shout out to @gasinvein for the original suggestion.
=> Replace Arch specific kernel copy hack with more generic solution

machine.go
Busybox uses only the modules.{builtin,dep,alias,symbols}.
Any other files, such as the .bin ones are kmod specific, so we don't
need to bother with them.
=> machine: copy only selected modules.* files

backend.go
Otherwise the --help screen will not print it, even though we'll accept
the value at runtime.
@sjoerdsimons was it omitted deliberately?
=> backend: Add qemu to the list of backend names

backend.go, backend_qemu.go, backend_uml.go, machine.go
With recently the former was reworked from list of modules and their
respective dependencies (all of which including relative path and
extension) to a modules that we use.
The only difference between the two is - virtio and virtio_ring. Both of
those are low level dependencies of the other virtio modules.
So just remove the extra function/array and consistently use
InitModules() across the board.
As follow-up on @santoshmahto7 's work in https://github.com/go-debos/fakemachine/pull/62
=> backend: remove InitrdModules() in favour of InitModules()

README.md
Github renders consecutive lines into an alinea.
The added triple backticks protect
-v, --volume=                     volume to mount
-i, --image=                      image to add
-e, --environ-var=                Environment variables (use -e VARIABLE:VALUE syntax)
to become
-v, --volume= volume to mount -i, --image= image to add -e,
--environ-var=  Environment variables (use -e VARIABLE:VALUE syntax)
=> Some README.md formatting

.github/workflows/ci.yml, machine_test.go
Currently we only run the tests on the qemu backend, which
misses all of the user-mode-linux backend functionality;
specifically fakemachine setup/teardown steps. We need to be
able to reliably test all backends in CI to be able to merge
any related changes with any confidence.
For now, only testing on the Debian base containers is
supported. More container baselines may be added as follow-up
pull requests.
Requires https://github.com/go-debos/test-containers/pull/11
=> Run CI tests on user-mode-linux backend on Debian

machine.go
Couple of small changes making the module.dep generation code a little cleaner and simpler. Namely:
- stop passing extension/suffix array as argument - it's constant data
- remove unneeded sorting of modules.dep contents
=> Simplify module handling

machine.go
Debian Unstable (and Fedora) has split systemd-resovled into a separate package which enables systemd-resolved as the default name resolver at install-time. Because of this, we cannot simply depend on systemd-resolved in the distro packaging as this may cause the default name resolver to change to systemd-resolved for some users.
If the user does not have system-resolved installed, fakemachine will currently fails with any action which requires hostname resolution:
2022/09/19 10:49:09 ==== debootstrap ====
2022/09/19 10:49:09 Debootstrap | W: Unable to read /etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory)
2022/09/19 10:49:09 Debootstrap | W: Unable to read /etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory)
2022/09/19 10:49:09 Debootstrap | I: Target …
=> Ensure systemd-resolved binary is available at runtime

machine_test.go
- Fix spelling in a unit test name
- Don't attempt to recover failed unit tests
=> Misc test improvements

backend_qemu.go
Currently we get a useful warning like:
9p: Multiple devices detected in same VirtFS export, which might lead to file ID collisions and severe misbehaviours on guest!
You should either use a separate export for each device shared from host or use virtfs option 'multidevs=remap'!
So let's add the option to avoid the issue. Requires QEMU >= 4.2.0
[Emil Velikov]
- Rebase, tweak commit message
=> backend_qemu: Avoid file ID collisions when multiple mounts share the same host path

.gitignore
Currently we match any file or folder called fakemachine, which means that any changes to files in b/cmd/fakemachine/ have to be forced via "git add --force"
Signed-off-by: Emil Velikov <emil.velikov@collabora.com>
=> gitignore: Correctly match fakemachine binary

machine_test.go
Current error message is a copy/paste from another test - correct that.
=> test: provide unique error messages on TestMemory() failure

machine.go, machine_test.go
If a mountpoint doesn't exist on the host, the backend
will fail to mount it and results in an ugly error
from the backend:
$ fakemachine -v /null
qemu-system-x86_64: -virtfs local,mount_tag=virtfs-5,path=/null,security_model=none: cannot initialize fsdev 'virtfs-5': failed to open '/null': No such file or directory
fakemachine: error starting kvm backend: <nil>
Check if a mountpoint exists before attempting to start
the backend.
Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>
=> Check mountpoints exist on the host early

backend.go
The qemu backend is only useful for CI testing where KVM isn't available. Do not allow users to automatically choose this backend as it is far too slow for regular use.
Let the CI and power-users opt-in to using this backend by manually selecting it (either from the API or by passing --backend=qemu).
=> Do not automatically select the qemu backend

machine.go
Fixes #148 
The module copying code already maintains a map of copied modules, so things aren't copied twice, so this shouldn't have too much of a performance impact.
This allows me to successfully boot the Ubuntu kernel mentioned in the issue report.
=> Recurse indirect module dependencies

cpio/writerhelper.go
This lets callers distinguish the type of error that occurred.
=> cpio: Wrap errors with %w

backend.go, backend_qemu.go, backend_uml.go, machine.go
This adds infrastructure for support different types of host systems, specifically adding arm64 support.
Tested on an rpi4 with Debian bullseye
Based on a patch by Ryan Gonzalez <ryan.gonzalez@collabora.com>
=> Add support for arm64 hosts

backend_qemu.go
Instead of using the (default) qemu emulated e1000 card use a virtio-net card instead which should give a small performance boost.
=> qemu: Use virtio network card rather then e1000

backend_qemu.go
Debian kernels tend to be build with a default console loglevel of 7, but other distributions such as arch may not. To get consistent behaviour for show-boot mode
=> qemu: explicitly set kernel log level

backend_qemu.go, backend_uml.go
If plymouth is installed in the host, the service  will be started during
the fakemachine's boot sequence. When plymouth starts, it attempts to
clear all of the the serial consoles which in turn causes the host's
shell to be cleared.
If fakemachine is ran with --show-boot this causes the boot log to be
lost and can also cause strange artifacts on the shell (e.g. missing
characters).
Add plymouth.enable=0 to the kernel arguments to stop plymouth from
starting during the machine's boot. The uml backend has the quiet parameter
which was added to achieve the same goal, so unify the kernel arguments
between the backends.
=> Disable plymouth boot splash

.golangci.yml, backend.go, cmd/fakemachine/main.go
This linter primarily checks that errors are wrapped with %v. Enable it & fix the lint errors which occur.
=> Enable errorlint linter & fix lint errors

cmd/fakemachine/main.go, go.mod, go.sum, machine.go, machine_test.go
The various fakemachine Run* functions end up running the provided commands in a shell, so add escaping to the arguments
=> Shellescape command line arguments

.github/workflows/ci.yml
kvm is the recommended backend for fakemachine; Unfortunately github hosted runners don't support virtualization. Luckily the debos organisation now has a kvm supported self-hosted runner sponsored by Collabora
=> Also run tests on self-hosted kvm runner

backend.go, backend_qemu.go, backend_uml.go, machine.go
Older versions of systemd-networkd-wait-online (e.g. <253) will happily just exit without error if no links are available. This causes a race condition where in some cases a fakemachine will be created with no network interface.
Fix this by giving the network interface a proper name when it is created and waiting for that specific network interface to go online.
=> Fix systemd-networkd-wait-online race

.github/workflows/ci.yml
Dependencies are slowly moving to newer minimal golang version making it impossible to update them while still supporting Debian bullseye. Drop requiring support for that version now that bookworm has been out for quite a while
=> Drop support for Debian bullseye/golang 1.15

.github/workflows/ci.yml
In go-debos/test-containers#30 we simplified the test containers by only creating one container for both fakemachine/debos instead of creating separate containers for each project. Use the new container.
Draft because:
- Depends on https://github.com/go-debos/test-containers/pull/30
- Container tag needs to change to `main`
=> ci: use generic test container

.github/workflows/ci.yml
With the github upgraded to newer/bigger runners virtualisation seems to work so run those tests on the github runners again
=> Use github runners for kvm tests

machine.go
Debian's kmod now builds with `--with-module-directory=/usr/lib/modules`[1]
(while the default is `--with-module-directory=/lib/modules`) which means
that `modinfo` now outputs module paths with `/usr` prefix already.
In fakemachine, on merged-usr systems, modules are copied into the initrd
with a prefixed path of `/usr`, no matter the system path produced by modinfo.
This means that modules are now copied into the wrong place, e.g /usr/usr/....
Fix compatibility with kmod built with /usr prefixed module-directory by
ensuring the module destination path has a prefix of /usr, rather than
always prefixing the destination path with /usr.
[1]: https://salsa.debian.org/md/kmod/-/commit/3306fbb10a8ff6c3bd643437e8f29353872524fd
Fixes: https://github.com/go-debos/fakemachine/issues/194
=> Fix compatibility when kmod module_directory prefixed with /usr

backend_qemu.go, backend_uml.go, machine.go
ioutils has been depreciated since Go 1.19; since Go 1.16 [bookworm] the same functionality is provided by the io or os packages. Use the new packages instead.
=> Replace depreciated functions from ioutils package

.github/workflows/ci.yml, backend_qemu.go, backend_uml.go, cmd/fakemachine/main.go, machine.go, machine_test.go
The sector size is added at drive level, so it's correctly reported by the kernel, allowing userland software to works without overriding the values. UML backend doesn't support alternate sector size since the ubd driver hardcode the 512 bytes sector size. (arch/um/drivers/ubd_kern.c)
=> Add method to override the images sector size

.github/workflows/ci.yml, cmd/fakemachine/main.go
This 'version' option prints the fakemachine version. Fix #200
=> cmd: Add 'version' option

backend.go, backend_uml.go
Remove user-mode-linux backend from automatic backend selection & allow user-mode-linux backend to be used manually along with a warning. Remove the user-mode-linux CI tests.
=> Deprecate user-mode-linux backend
